services:
  car-rental:
    container_name: car-rental
    restart: always
    image: node:20.10.0
    ports:
      - 5001:3006
    environment:
      - NODE_ENV=production

    volumes:
      - ./:/usr/src/rentgo
    working_dir: /usr/src/rentgo

    networks:
      - production

    # FOR PRODUCTION
    command: sh -c "npm ci --include=dev && npm run build && mkdir -p dist/views dist/public && cp -r src/views/. dist/views && cp -r src/public/. dist/public && npm run start"

networks:
  production:
    driver: bridge
